version: '3.9'

# Disclaimer: this is just an example, not intended to be a production configuration.

services:
    lynx:
        image: yuafox/lynx-iberian:2023.1
        stdin_open: true
        tty: true
        ports:
            - "8080:8080"
        volumes:
            - ./config:/app/config
            - ./plugins:/app/plugins
            - ./storage:/app/storage
        environment:
            DB_URL: "mysql://root:password@mysql/lynxiberian?createDatabaseIfNotExist=true"
            LYNX_USERNAME: lynx
            LYNX_PASSWORD: lynx
            NODERED_HOST: node-red
            # Add it if you want to use the twitter plugin
            TWITTER_KEY: 0
            TWITTER_SECRET: 0
        depends_on:
            -   mysql
    node-red:
        image: nodered/node-red:latest
        # Automatically install lynx iberian node red nodes
        entrypoint: /bin/sh -c "npm i node-red-contrib-lynx-iberian && ./entrypoint.sh"
        environment:
            - TZ=Europe/Amsterdam
        ports:
            - "1880:1880"
        volumes:
            - ./node-red-data:/data
    mysql:
        image: mysql
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - "./mysql-data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: password
