version: '3.9'

services:
    lynx:
        image: yuafox/lynx-iberian:2023.04
        restart: unless-stopped
        ports:
            - "8080:8080"
        volumes:
            - ./config:/app/config
            - ./plugins:/app/plugins
            - ./storage:/app/storage
        environment:
            DB_URL: "mysql://root:password@mysql/lynxiberian?createDatabaseIfNotExist=true"

            LYNX_USERNAME: lynx
            LYNX_PASSWORD: lynx
            
            # SOCIAL MEDIA INTEGRATION
            # Uncomment to use it

            # TELEGRAM_TOKEN: "token"
            # TELEGRAM_CHAT: "chat"

            # MASTODON_DOMAIN: "botsin.space"
            # MASTODON_TOKEN: "xxxx"

            # TUMBLR_BLOG: "foxeseveryhour"
            # TUMBLR_CONSUMER_KEY: "token"
            # TUMBLR_CONSUMER_SECRET: "token"
            # TUMBLR_TOKEN_KEY: "token"
            # TUMBLR_TOKEN_SECRET: "token"

            # TWITTER_API_KEY: "token"
            # TWITTER_API_SECRET: "token"
            # TWITTER_CLIENT_ID: "access_token"
            # TWITTER_CLIENT_SECRET: "access_token"

            # DISCORD_TOKEN: "Token"
            # DISCORD_ACTIVITY: "Test"
        depends_on:
            -   mysql
    mysql:
        image: mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - "./mysql-data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: password
