version: '3.9'

# Disclaimer: this is just an example, not intended to be a production configuration.

services:
    foxeseveryhour:
        image: yuafox/lynx-iberian:2023.04
        restart: unless-stopped
        ports:
            - "8080:8080"
        volumes:
            - ./config:/app/config
            - ./plugins:/app/plugins
            - ./storage:/app/storage
        environment:
            DB_URL: "mysql://root:password@mysql/lynxiberian?createDatabaseIfNotExist=true"

            LYNX_USERNAME: lynx
            LYNX_PASSWORD: lynx
            NODERED_HOST: node-red
            
            # SOCIAL MEDIA INTEGRATION
            TELEGRAM_TOKEN: "token"
            TELEGRAM_CHAT: "chat"

            MASTODON_DOMAIN: "botsin.space"
            MASTODON_TOKEN: "xxxx"

            TUMBLR_BLOG: "foxeseveryhour"
            TUMBLR_CONSUMER_KEY: "token"
            TUMBLR_CONSUMER_SECRET: "token"
            TUMBLR_TOKEN_KEY: "token"
            TUMBLR_TOKEN_SECRET: "token"

            TWITTER_KEY: "token"
            TWITTER_SECRET: "token"
        depends_on:
            -   mysql
            
    node-red:
        image: yuafox/node-red-tensorflow
        restart: unless-stopped
        volumes:
            - ./node-red:/data
        ports:
            - "1880:1880"
    mysql:
        image: mysql
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - "./mysql-data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: password
